// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB25HMpavE39De4pvwKeFevrh8oxRmbVa4',
    appId: '1:1080747551010:web:6bc739f76c30f954ef1d7b',
    messagingSenderId: '1080747551010',
    projectId: 'pixelsoft-ede43',
    authDomain: 'pixelsoft-ede43.firebaseapp.com',
    storageBucket: 'pixelsoft-ede43.appspot.com',
    measurementId: 'G-9F885PK0E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb7NhlAMnjTv2kxt71bS1nrJGznncAbC4',
    appId: '1:1080747551010:android:8938e6d3b3e992e4ef1d7b',
    messagingSenderId: '1080747551010',
    projectId: 'pixelsoft-ede43',
    storageBucket: 'pixelsoft-ede43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPzAdIa9iEEKodmqI68uWQ3KmTDeQE-Wo',
    appId: '1:1080747551010:ios:4ab13f066f90914bef1d7b',
    messagingSenderId: '1080747551010',
    projectId: 'pixelsoft-ede43',
    storageBucket: 'pixelsoft-ede43.appspot.com',
    iosBundleId: 'com.pixelsoft.pixelsoft2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPzAdIa9iEEKodmqI68uWQ3KmTDeQE-Wo',
    appId: '1:1080747551010:ios:4ab13f066f90914bef1d7b',
    messagingSenderId: '1080747551010',
    projectId: 'pixelsoft-ede43',
    storageBucket: 'pixelsoft-ede43.appspot.com',
    iosBundleId: 'com.pixelsoft.pixelsoft2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB25HMpavE39De4pvwKeFevrh8oxRmbVa4',
    appId: '1:1080747551010:web:6c67ccb147690902ef1d7b',
    messagingSenderId: '1080747551010',
    projectId: 'pixelsoft-ede43',
    authDomain: 'pixelsoft-ede43.firebaseapp.com',
    storageBucket: 'pixelsoft-ede43.appspot.com',
    measurementId: 'G-NR9SJTYHSW',
  );
}
